name: Latest Blog Posts Workflow

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sunandobhattacharya.vercel.app/rss.xml, https://sunandobhattacharya.vercel.app/feed.xml"
          max_post_count: 5
          template: "$newline- [ $title ]($url) <br/> $description"
